### PR TITLE
BUGFIX: Only add labels to child core

### PR DESCRIPTION
**Pull request by mattayes**
# Bug

Before this change, when one used `With()` with labels, the labels would be added to both the parent and child core. This behavior isn't correct: With() should only add labels to the child. Otherwise, if someone calls `With()` on the global logger, ALL subsequent uses of the global logger will include that field.

# Changes

This PR copies `c.permLabels` before adding `lbls`, so new labels are only added to the child core. This change includes a regression test.

### CODE REVIEW

**Comment by mattayes** [comment]
Hi @asahasrabuddhe, checking in: will you have time to review this PR? The fix is in production at my company and labels are now working correctly.

**Review by asahasrabuddhe — APPROVED** [review]
LGTM

**Comment by mattayes** [comment]
Hi @asahasrabuddhe, I'm trying to download the latest release and am running into some errors:

```bash
$ go get -d go.ajitem.com/zapdriver@v1.4.1
go get go.ajitem.com/zapdriver@v1.4.1: unrecognized import path "go.ajitem.com/zapdriver": parse https://go.ajitem.com/zapdriver?go-get=1: no go-import meta tags ()
```

It looks like the `go-import` meta-tag for [go.ajitem.com/zapdriver](https://go.ajitem.com/zapdriver) is [malformed](https://go.dev/ref/mod#serving-from-proxy): it's missing the repository root path.

**Comment by asahasrabuddhe** [comment]
> Hi @asahasrabuddhe, I'm trying to download the latest release and am running into some errors:
> 
> ```shell
> $ go get -d go.ajitem.com/zapdriver@v1.4.1
> go get go.ajitem.com/zapdriver@v1.4.1: unrecognized import path "go.ajitem.com/zapdriver": parse https://go.ajitem.com/zapdriver?go-get=1: no go-import meta tags ()
> ```
> 
> It looks like the `go-import` meta-tag for [go.ajitem.com/zapdriver](https://go.ajitem.com/zapdriver) is [malformed](https://go.dev/ref/mod#serving-from-proxy): it's missing the repository root path.

Sorry about this issue you had to face. Could you try downloading it again?

**Comment by mattayes** [comment]
@asahasrabuddhe Thanks for fixing that, it works great now! 🚀

**Pull request merged**
